### ISSUE TITLE
Required fields

### ISSUE THREAD

**Issue by smunaut** [gnuradio/SigMF#1]
Looking at the current list of required global fields, I see : ```core:datatype```, ```core:license```, ```core:date```, ```core:url```, ```core:hash```, ```core:version```

For some, it's obvious that they are really required because you can't even make sense of the data, like ```core:datatype```.

For others the effort to a writer software to provide is basically nil because good defaults are available like ```core:date``` (which can default to NOW), ```core:url``` (which can default to just the data filename), ```core:version``` (which can just default to a constant string of the version of the spec used when writing that software ...).

But things like ```core:license```, or ```core:hash```, there is just no good default values.
To have any kind of validity, the license would have to be explicitly selected by the user and defaulting to 'Non Public / Private / ...' might as well just omit the field all together.
As for ```core:hash```, this is not trivial to compute. A writer software would have to include hashing code and process that live.

Now I agree that if we want those files to be shared publicly, those fields would be good, but then I'd say those fields are more a requirement of the data sharing platform than requirements to be a valid metadata file.

Personally I would keep the "mandatory" / "required" flags for fields where there is really no other choice because without it a software just can't make any sense of the data.

**Comment by smunaut** [comment]
The schema has been updated, but including the rationale of why/when a field should be set as required would be good. Including to help guide people developing and specifying their extensions.

**Comment by bhilburn** [comment]
Agreed with @smunaut's comment about providing rationales. Leaving this issue open as a TODO.

**Comment by bhilburn** [comment]
See #12

**Comment by bhilburn** [comment]
#12 has been merged!
