### ISSUE TITLE
ION GNSS Sofware Defined Receiver Metadata Standard

### ISSUE THREAD

**Issue by Teque5** [gnuradio/SigMF#100]
Heads up that ION is working on a new SDR standard for sampled GNSS data and we should perhaps try to help them a bit. They currently only have a working group drafting rev 2 at the moment, so there is still time: [Github](https://github.com/IonMetadataWorkingGroup) & [Website](http://sdr.ion.org/).

**Comment by bhilburn** [comment]
Thanks for opening this issue, @Teque5. @marcusmueller and I were just discussing this on Twitter, too, following a tweet from Lime Micro about the GNSS-SDR-MD effort.

We are trying to reach out to the folks involved and have a conversation about their effort and goals more broadly, and discuss the relation to SigMF. I'll update this issue with more once we get in touch.

**Comment by Teque5** [comment]
Great; I sent them an email pointing to this issue as a place to respond.

**Comment by bhilburn** [comment]
I've tried reaching out to the people involved with the ION GNSS effort, but have never heard anything back, unfortunately. If anyone knows someone involved with that and they are willing to chat with us, please tell them to get in touch!
