### ISSUE TITLE
Ambiguity on annotation specification

### ISSUE THREAD

**Issue by samuellush** [gnuradio/SigMF#102]
My team's current project makes two assumptions about SigMF metadata that seem ambiguous in the specification:

1. Annotations must be within a single capture; that is, one annotation cannot span multiple captures
2. The frequency range of an annotation can be wider than bandwidth of a particular capture (for instance, if the capture spans from 2 to 3 MHz but the annotation's freq_lower_edge and freq_higher_edge are 1 and 4 MHz respectively)

Do these assumptions follow the official interpretation of the spec?

**Comment by bhilburn** [comment]
Hey @samuellush! 

1. Can you point me to the part of the spec that is causing confusion about this? I don't think there is anything in the spec that would limit annotations across captures, so if you see language that confuses that point, I for sure want to address it.

2. You're right! There is no requirement that annotations fit within the frequency edges of the capture.

**Comment by samuellush** [comment]
Thanks for the feedback, we're clear about #1, we just wanted to ensure that we're interpreting correctly. In the future we'll keep this in mind with #2.
