### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by dbouquin** [gnuradio/SigMF#109]
There was [a great Code of Conduct](https://github.com/SETIatHCRO/grhack/blob/master/CODE_OF_CONDUCT.md) on the grhack repo from the Contributor Covenant. Any objection to adapting it to fit SigMF?

**Comment by bhilburn** [comment]
Not in the least, and thanks so much for pointing out this rather embarrassing oversight.

The CoC has been added to this repo as of  336fcec and can be found here:
https://github.com/gnuradio/SigMF/blob/master/CODE_OF_CONDUCT.md
