### ISSUE TITLE
Supplemental Information String per Object

### ISSUE THREAD

**Issue by adamchicks** [gnuradio/SigMF#110]
It would be nice if we could have a value that linked to further supplemental information in each object. For instance, in the antenna object, if I could provide a directory link or url to the spec sheet or any files that don't necessarily condense down into the SigMF format.

**Comment by bhilburn** [comment]
@adamchicks - That's a really interesting point. So, in the work that got done at the SETI hackfest, we have designed out a way to more concretely describe the hardware of each sensor that has make a recording, and of the experimental setup as a whole for a collection of recordings. This seems like a natural thing to add to that enhancement.

That said, the phrasing of your description also makes it sound like you were thinking about it from a more general perspective. There isn't anything in the spec right now that would prevent someone from adding a "more information" field, whatever that might look like, to their own extension namespace (e.g., `antenna`), but this has me spinning on what makes sense from a template schema perspective for extension namespaces.

@adamchicks - If ^^^ sounds like the solution you are looking for, then it should be covered in the changes coming down the pipe! Let me know =)

**Comment by adamchicks** [comment]
Sounds like something might be in the works. Thanks for the reply. I'll keep my eye on future releases.
