### ISSUE TITLE
how to read sigmf-data file?

### ISSUE THREAD

**Issue by p577665228** [gnuradio/SigMF#114]
how to read sigmf-data file? Is here any python tool to read sigmf-data file?

**Comment by n-west** [comment]
Hi @p577665228, I think this repository has some basic python tooling. I am personally a big fan of keeping it simple with python. Unless you have a code generator to give you nice type definitions for fields, you can just use `json` to give you python dicts, lists, etc. I usually do something like the following:

```
import json
import numpy as np

with open("myrecord.sigmf-meta", "r") as f:
    md = json.loads(f.read())
if md["global"]["dtype"] == "cf32_le":
    samples = np.memmap("myrecord.sigmf-data", mode="r", dtype=np.complex64)
elif md["global"]["dtype"] == "ci16_le":
    samples = np.memmap("myrecord.sigmf-data", mode="r", dtype=np.complex64)
    # Convert samples to float if you want...
```

**Comment by p577665228** [comment]
Thanks you. Your script works. But it seems to be unreasonable that cf32_le equal to np.complex64 Instead of np.complex32. Even though there is no datatype np.complex32, but when I use np.complex64, I will get some strange value like A = (-3.689349e+19+1.0971746j), where -3.689349e+19 is to big.

**Comment by p577665228** [comment]
Thank you, your script works. But cf32_le equals np.complex64 instead of np.complex32 seems unreasonable. Even if there is no data type np.complex32, when I use np.complex64, I get some strange values, such as A = (-3.689349e + 19 + 1.0971746j), where -3.689349e + 19 is large. Note the datatype of sigmf-data I read is cf32 rather cf32_le, what's the right np.complex* for cf32.

**Comment by n-west** [comment]
This is just two different ways of describing the same thing.

See the numpy docs for the description of complex64 (https://docs.scipy.org/doc/numpy-1.13.0/user/basics.types.html):
`complex64  Complex number, represented by two 32-bit floats (real and imaginary components)`

See the SigMF description of cs32_le:
`So, for example, the string "cf32_le" specifies complex 32-bit floating-point samples stored in little-endian`

Both are describing interleaved I and Q components each of a 32-bit float. Together they form a complex float. The numpy description comes from the bit width of the entire number whereas sigmf is describing the bit width of individual components (just the I and just the Q).

Is your data actually a complex float? If so, that's how you read it. Otherwise complex int or int16 might be what you're looking for

**Comment by n-west** [comment]
There is perhaps room for improvement in SigMF to explicitly say that the two parts of a complex number are each 32-bit floats similar to the way numpy specifies it. Feel free to suggest an improvement in that wording. You're currently the best expert on clearly phrasing that if it's something you're just now learning and were confused by previously.

**Comment by bhilburn** [comment]
Thanks for the question, @p577665228, and thanks for providing great advice, @n-west!

Interesting point re: clarifying what it means for something to be interleaved I & Q in the spec, @n-west. You're right that there is probably room for that, there. I'll open an issue on it now.

**Comment by TiantianZhang** [comment]
> There is perhaps room for improvement in SigMF to explicitly say that the two parts of a complex number are each 32-bit floats similar to the way numpy specifies it. Feel free to suggest an improvement in that wording. You're currently the best expert on clearly phrasing that if it's something you're just now learning and were confused by previously.



> Thank you, your script works. But cf32_le equals np.complex64 instead of np.complex32 seems unreasonable. Even if there is no data type np.complex32, when I use np.complex64, I get some strange values, such as A = (-3.689349e + 19 + 1.0971746j), where -3.689349e + 19 is large. Note the datatype of sigmf-data I read is cf32 rather cf32_le, what's the right np.complex* for cf32.


hi，my problem is just same as your. I get it using the datatype cf32，float32. But the result is same, one of the number is bigger than other one.
python method just like the following:
f = scipy.fromfile(open(r"neu_m04643294-zipped.bin"), dtype=scipy.complex64,)
Have you solved the problems? Thanks

**Comment by gmabey** [comment]
Hi @TiantianZhang !

My observation from the one line of python that you posted is -- your challenge is a scipy/numpy one, and is not related to SigMF.

Best Regards,
Glen
