### ISSUE TITLE
Clarify Interleaved I&Q

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#118]
Per #114 , for users not previously familiar with dealing with datatypes and representations of interleaved I&Q samples, there is room in the spec for improvement in clarifying this. There's also the very small chance that someone might do something wildly unexpected, like mix & match datatypes in some bizarre complex representation, which I think technically would be allowed by the current spec.

Specifically, it's probably worth explicitly stating that sample pairs must be two numbers of the same datatype.

**Comment by kartiksadalage** [comment]
I would like to work on this

**Comment by bhilburn** [comment]
@kartiksadalage  - Fantastic! Do you need anything from me to take a pass on it? Otherwise, please feel free to file a PR and we can iterate if needed :)

**Comment by jacobagilbert** [comment]
I may be alone here, but I do not feel this is a necessary clarification.

**Comment by gmabey** [comment]
Meh, it doesn't hurt either, even if it isn't necessary.  Like, I agree it's 100% obvious to *anyone* who has worked with complex data, but the words I added in the pull request are valid and may prevent a question sent to this project by a naive reader.

**Comment by gmabey** [comment]
@bhilburn @jacobagilbert I'm looking at this issue as one of the [relatively] few things that needs to get resolved before a 1.0 release.  If there is a consensus that adding the language isn't necessary, we should be able to close the issue, no?  I guess I'm disappointed that an issue as trivial (and self evident!) as this is a hold-up, and I would like to request that somebody consider accepting my MR, or close the issue.

**Comment by bhilburn** [comment]
@gmabey - I saw your PR last week on this. It was a long weekend for the US, and I haven't had a chance to respond, yet (plus, I do things other than maintain SigMF at my day job 😅). Anyway, this issue isn't holding up the release. I would like to have this change, as I think it's a worthwhile change for people who have only ever worked with real samples rather than interleaved complex pairs.

**Comment by bhilburn** [comment]
Closed by merge of #126
