### ISSUE TITLE
Rogue `core:date` field, inconsistent `core:datetime` implementation in code

### ISSUE THREAD

**Issue by jrocnuck** [gnuradio/SigMF#121]
The main spec file (sigmf-spec.md) shows only 
core:datetime as a valid field (key in a dictionary) for the SigMF spec.

However, perhaps I'm missing something, there are a couple of places in the files that show date and time independently  (core:time and core:date).

The file SigMF/sigmf/schema.json line 31 shows core:date.
The file SigMF/tests/test_validation.py line 31 shows core:date.

The file SigMF/sigmf/schema.json line 76 shows core:time.
The file SigMF/tests/test_validation.py line 40 shows core:time.
The file SigMF/tests/test_validation.py line 40 shows core:time.
The file SigMF/tests/test_sigmffile.py line 36 shows core:time.
The file SigMF/example_metadata.py line 18 shows core:time.

It seems that all of these files need to be updated so that all example code and specification documentation are consistently agreeing on what the actual field name is.

**Comment by bhilburn** [comment]
You're correct, @jrocnuck. The code has deviated from the current version of the spec. `schema.json`. And, actually, that `global::core:date` field also appears in `global` of the JSON schema.

The "correct" instance of date/time is the `core:datetime` in the `captures` array. As you point out, that is currently written as `core:time` in those 5 files you call out, which is a typo.

Marking this as a bug, PRs welcome to fix.

**Comment by Teque5** [comment]
I just noticed that in `schema.json` it says `"core:sampling_rate"` but the spec indicates `"core:sample_rate"` too.
