### ISSUE TITLE
Tag a stable release

### ISSUE THREAD

**Issue by gmabey** [gnuradio/SigMF#122]
Hello!

I'm curious to know how the authors would define a "stable release" for this project.  From my perspective, there are two parts: the stability of the file format definition, and the completeness/buginess of the utilities for accessing that file format.

Like, I know those two issues are intertwined (to some extent) but what I really want to know is the stability of the Signal Metadata Format Specification.  I see that it's currently at v0.0.2 -- but given that it hasn't changed recently, is it effectively a 1.0?

Would you consider marking it as such?

**Comment by bhilburn** [comment]
Hey @gmabey! Yeah, that's a totally fair question. And you're right, the development of the spec itself and the tools that are packaged in this repo are very obviously related, but also could be treated independently in terms of maturity / stability.

Just to confirm current state: only stable release is v0.0.1, current head of `main` (I'm going to rename `master` branch) is showing v0.0.2 work-in-progress. There are milestones for both v0.0.2 and v0.1.0. The date I had set for target v0.0.2 release is way overdue.

Given the adoption and traction of the existing version, I agree, it's really owed it's own release that doesn't reflect an alpha-level semver tag. Assigning this to me.

**Comment by bhilburn** [comment]
@gmabey - Modifying my previous statement: I agree, we should be targeting v1.0.0. Expect to see organization around a milestone as such shortly.

**Comment by gmabey** [comment]
Thank you -- I was almost ready to ask for that very thing

**Comment by bhilburn** [comment]
Project and Milestone for v1.x created and tracking. Closing this discussion - if you are interested in taking on any of the bug fixes marked for the release, @gmabey, please feel free to comment in them! We'd love the help 🙂

**Comment by gmabey** [comment]
Would y'all be willing to set a target date for the 1.0.0 milestone?

**Comment by jacobagilbert** [comment]
We are still targeting before GRCon 21. The spec is very close.

**Comment by gmabey** [comment]
that's fabulous news, thank you!
