### ISSUE TITLE
Add short-form human or machine readable field to `annotations`

### ISSUE THREAD

**Issue by jacobagilbert** [gnuradio/SigMF#131]
As part of my review on #120, i noted that the `label` field is really a generally useful feature that should be in `core`. We currently have `comment`, however this is not specified as short form and may very well be a short sentence or something otherwise not machine readable.

We have the rfml.sigmf-ext but that has a number of problems for general use (mostly that if you use that extension, you are required to include an array of labels that fit into a single, fixed (for a given dataset) label hierarchy for every single annotation to remain compliant.

I propose the addition of an optional `core:label` or `core:description` field to `annotations` for a short-form human or machine readable string. The latter is consistent with the field currently in `global` and avoids conflicting with the `label` field in rfml.sigmf-ext. I also propose that there be an optional `core:included_labels` field in `global` for users to specify what labels are in the file (software utilities can easily do this automatically) to avoid requiring users to iterate over all annotations to know what is in the file.

**Comment by Teque5** [comment]
@jacobagilbert I think `core:label` implies a short description better than `core:description`. Maybe we want to limit this field to a certain number of characters for use in guis (20?).

If it were me I might put an ITU designator in there, which is only 8 chars: `11K2 F3E`.
