### ISSUE TITLE
Update readme to mention pypi availablility/limitations

### ISSUE THREAD

**Issue by nsbruce** [gnuradio/SigMF#132]
While this SigMF repos readme recommends installing from source, there is a release (0.0.1) available on pypi. The current readme examples don't run on 0.0.1 (`SigMFFile` doesn't exist for example).

The issue is that if someone runs  `pip install sigmf` then tries out the readme examples they don't work.

I am happy to push a small PR that indicates in the examples section that they apply to master and not necessarily to the releases.

**Comment by Teque5** [comment]
A better solution would simply to be to update the `sigmf` package in the pypi repo.

**Comment by Teque5** [comment]
It doesn't seem to work for this module, but a user should be able to do `pip install --upgrade sigmf` and it should pull directly from the github repo. Whoever owns the project over there should fix.

**Comment by bhilburn** [comment]
Ah, it would appear that, in fact, /I/ am one of two owners of that package, hah. I'll give that a go.

**Comment by bhilburn** [comment]
closing to track in #165
