### ISSUE TITLE
Use more specific filename extensions

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#14]
I was asked to review the SigMF specification by @bhilburn. It currently says:

> 3. The metadata file MUST have a `.meta` filename extension.
> 4. The dataset file MUST have a `.data` filename extension.

I recommend, instead, specifying a (closer to) globally unique pair of filename extensions. This allows uses such as:

* Registering editor/viewer applications in traditional desktop environments.
* An application deciding how to interpret a file in one of several possible formats by looking at the extension.
* A user web searching to find out what format the files they have are in.
* Registering in web server MIME type databases.

I suggest either `.sigmfm` and `.sigmfd` or `.sigmfmeta` and `.sigmfdata`, the choice depending on a weighting of clarity vs. shortness.

(Starting them with a common prefix also assures that the two files will sort next to each other if they are accompanied by more files with other extensions.)

**Comment by bhilburn** [comment]
How do folks feel about hyphenated extensions?

`.sigmf-meta` and `.sigmf-data`

**Comment by kpreid** [comment]
I'm not aware of any particularly strong reason to choose or avoid them. I can think of several vague FUDy reasons to avoid them: I imagine there might, somewhere in the world, be a thing that thinks filename extensions can only contain letters/numbers. It's one character longer. It might be taken as two tokens in a keyword search.

**Comment by bhilburn** [comment]
Okay, #45 is up for this!

**Comment by bhilburn** [comment]
Fixed by #45.
