### ISSUE TITLE
Missing scheme key in SigMFFile 

### ISSUE THREAD

**Issue by Deschain** [gnuradio/SigMF#148]
Due to the recent changes in the scheme (mainly 8482020c6d30aa84e8f371a061867c1fd7c55be3) I found some missing keys inside SigMFFile. For example, "core:label" was added in 259206243e13f63a1793a07972c3d916863183b8 but is not available in SigMFFile.

**Comment by bhilburn** [comment]
@Deschain  - Great catch! Is this something you would be up for submitting a PR for as a contributor, by chance? ☺

(If not, no worries, but if you'd like to contribute spec-code into the project I want to make sure you have the opportunity!)

**Comment by jacobagilbert** [comment]
This specific item is addressed, I did a quick pass and believe all fields are properly updated.
