### ISSUE TITLE
Move optional dependencies from required dependencies

### ISSUE THREAD

**Issue by Deschain** [gnuradio/SigMF#149]
There are optional dependencies (pysimplegui) in the required dependencies. It would be better to put these things (the GUI and the webapp) in the [optional dependencies](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies)

**Comment by bhilburn** [comment]
Great catch, @Deschain.

@Teque5 - Assigning this one to you, have a look when you get a chance? 🙂
