### ISSUE TITLE
Uncertainty about semantics of annotation's sample_start 

### ISSUE THREAD

**Issue by povik** [gnuradio/SigMF#153]
I am a bit uncertain about the semantics of annotation's `core:sample_start`. Does the index contain the offset specified with global `core:offset`? I implicitly take it that yes, it does, but I suggest adding an explicit statement of this, maybe a general one, like "All sample indices in the SigMF metadata take into account the offset specified in `core:offset`.".

**Comment by bhilburn** [comment]
@povik - Your assumption is correct, and that's a great recommendation for a clarification. Will be easy to include in v1.0.0.

**Comment by povik** [comment]
Great. Thanks for the confirmation.
