### ISSUE TITLE
Remove "datapath".

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#16]
I was asked to review the SigMF specification by @bhilburn. It currently says:

> The following names are specified in the core namespace and should be used in the global object:
> 
> datapath    The filepath to the dataset file described by the SigMF file. The path can be absolute or relative.

I believe this is unnecessary and harmful.

* Given that the field is currently specified as required, this implies that the metadata file must be rewritten any time the file set is renamed. This is an inconvenience for people organizing their files.
* It is of unclear meaning if the files are used in a context which does not have a filesystem, or does not have a filesystem in common between the author and the reader of the file.
* The format of pathnames is operating-system-dependent. (For example, as currently written, a Windows-based author is free to specify a relative path using backslashes, which a Unix-based reader would then misinterpret.)
* It is a security risk. For example, my SDR receiver application ShinySDR is a web app. Suppose it allowed users to upload SigMF files and replay them. It is then obligated to check that `datapath` is valid (or, practically, to rewrite it); otherwise `{"datapath": "/path/to/sensitive/file/of/your/choice"}` would allow the remote user to read back that file — at least in FFTed form, which might be enough for interesting attacks; if nothing else to find out the existence and size of the files.

Instead, the specification should simply require the names of the two files, when applicable, to be identical except for extension.

**Comment by bhilburn** [comment]
I think you have really good points, here, @kpreid.

Regarding this:

> Instead, the specification should simply require the names of the two files, when applicable, to be identical except for extension.

This is still encumbered by your first bullet:

> * Given that the field is currently specified as required, this implies that the metadata file must be rewritten any time the file set is renamed. This is an inconvenience for people organizing their files.

But perhaps that's simply a necessary evil for associating the files together.

Thoughts?

**Comment by kpreid** [comment]
@bhilburn I'm not sure what you mean. Are you referring to the fact that the two files would have to be renamed in the same way? 

If so, I think that is still much better than `datapath` because it is an operation that is easily accomplished with a single tool (one's file manager), and it's fairly obvious that it ought to be done, whereas `datapath` is hidden and requires two tools (one to rename files and one to edit the metadata file).

**Comment by bhilburn** [comment]
Okay, please review & comment on #46.

**Comment by bhilburn** [comment]
Closed by merge of #46.
