### ISSUE TITLE
Update pip to current v1.0.x release.

### ISSUE THREAD

**Issue by Teque5** [gnuradio/SigMF#165]
@bhilburn let's get this thing install-able through `pip` asap.

**Comment by Teque5** [comment]
This is actually a duplicate of #132. 

- update current version in pypy (eaaaaasy)
- make it so when you run `pip install --upgrade sigmf` it pulls from github (this must be easy but I haven't done it)

**Comment by bhilburn** [comment]
@Teque5 - I actually don't see a way to make it pull from github. Have you done this in PyPy before, by chance?

**Comment by bhilburn** [comment]
This needs to happen after we've tagged v1.0.0 so we have the release tarball

**Comment by Teque5** [comment]
@bhilburn I've poked around a bit on pypy and looked at packages that I frequency update with `--update` and it seems they must just have an automated process to update pypy.org with a weekly release. Specifically I looked at [yt-dlp](https://pypi.org/project/yt-dlp/#history) and they publish 3-4 times per month.

**Comment by tammojan** [comment]
Automating uploading to pypi is usually done as a continuous integration job through Github actions. You can configure to package and upload the main developement branch on every commit, or just tagging a release. For sigmf, that needs to be stable, in principle uploading only tagged releases is the cleanest, but in the case that the development branch is years ahead of the last release, sometimes releasing the development branch on a daily or weekly bases is arguably better.

At any rate I think the README in this repository should *also* mention that the version in this repository may be newer than the one that `pip install sigmf` will give you, and that the examples on the readme may not work with the pip version (as suggested in #132). Even after the v1.0.0 release, the development version on github will be newer than what is on pypi.

**Comment by bhilburn** [comment]
"update current version in pypy (eaaaaasy)" this part was a joke, right, @Teque5? 😂

@tammojan - This is really great guidance. Thank you!

**Comment by tammojan** [comment]
May I ask what's holding back the release on pypi, now that the release has been tagged? It's really just a matter of following the instructions at https://packaging.python.org/en/latest/tutorials/packaging-projects/ . I'm happy to help out if necessary.

**Comment by Teque5** [comment]
Yea I agree maybe you can help out @bhilburn. I think ben wanted the 1.0.0 pip version to be a big release but I think what we have is great - there can always be a v1.0.1.

Within our automated build process we have to git pull & install the package but i'd prefer if we were able to do `pip install`.

**Comment by bhilburn** [comment]
Fully intend to make the current tag the pip v1.0.0 package, just haven't had a chance to do it, yet. 

@tammojan - I'd love the help! If you have the time to create the source archive & built distribution, that would be amazing 🙂

**Comment by tammojan** [comment]
Sure, here they are. It is the git tag SigMF-v1.0.0, where I manually set the version to 1.0.0 (that was overlooked upon releasing, and version 1.0.1 with the fix has not been released - I think the manual solution is acceptable).
[dist.zip](https://github.com/gnuradio/SigMF/files/7895708/dist.zip)

**Comment by Teque5** [comment]
At the same time here we should sort out the tag names:
- `SigMF-v1.0.0` → `v1.0.0`
- `SigMF-v1.0.0-rc1` → <delete>
- `v0.0.1` → <leave>
And when we accept PRs we should increment that bugfix value in `__version__`.

**Comment by gmabey** [comment]
I would think that incrementing `__version__` only on releases would be
more appropriate, even though it's actually inaccurate.  Maybe giving it a
`-git` suffix after the first PR is accepted ... surely other projects have
put much more thought into this issue than I have, but I'm totally unaware
of how other projects handle this.

**Comment by bhilburn** [comment]
@tammojan - Thank you so much!

@tammojan, @gmabey, @Teque5  - v1.0.0 is live on PIP 🎉

@Teque5 agreed on tag clean-up
