### ISSUE TITLE
Omitting namespace strings?

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#17]
The spec currently says:

> The format of the name/value pairs is: 
>
> `"<namespace:>name": value,`
>
> Where the namespace string should be replaced with the name of the namespace in use, or omitted entirely (including the colon).

I think that was originally written before we had completely fleshed out the concept of namespaces. Do we really want to allow omission of the namespace string? Allowing the omission of `"core"`, for example, actually means that it's not semantic, which isn't something I agree with.

**Comment by smunaut** [comment]
should be required always IMHO.

**Comment by bhilburn** [comment]
Okay, see #32 and review, please!

**Comment by bhilburn** [comment]
Closed by #32
