### ISSUE TITLE
Allow for data file name to be explicitly stated in a SigMF metadata file.

### ISSUE THREAD

**Issue by jsallay** [gnuradio/SigMF#170]
Right now, the name of the SigMF data file is assumed from the metadata filename with a required file extension.  We may not always be operating in an environment where we have control over the data filename or we may want to describe metadata from a non SigMF data file.

If we allow for the SigMF metadata file to explicitly specify the data file name it allows for the above cases and can also enable new cases.  It also makes the metadata file more self contained by removing an assumption.

**Comment by jacobagilbert** [comment]
As a point of reference, the way deepsig does this (not actually supported by the core spec) is with three extension global fields:

```json
{
   "global": {
        ...
        "deepsig:data_file": "file_name.file_extension",
        "deepsig:data_size": 40000000,
        "deepsig:data_offset": 0
    },
    ...
}
```

This allows associating sigmf metadata with data files that have some sort of header/trailer (e.g.: MIDAS blue files).

**Comment by bhilburn** [comment]
Per our discussion at GRCon'21, I'm totally on-board with this, and think it should be a feature for v1.0.0. Marking it as such now.

@jacobagilbert - I'm confused by DeepSig's approach. Is that offset field different than the offset fields already provided? I'm also wary of a datasize field, for what it's worth. We had long discussions about that early on and decided to leave it out as the actual filesize should be groundtruth.

My thinking was we just add:

```json
{
   "global": {
        ...
        "core:dataset": "filename",
        ...
    },
    ...
}
```

And carry the same requirements regarding directory locality as existing Recordings. Thoughts?

**Comment by jacobagilbert** [comment]
@bhilburn the `deepsig:data_offset` field describes how many bytes into the data file the first sample starts at to account for things like MIDAS blue files which have a 512B header before data starts. This is an important field to include as a single file composed of a header followed by data is fairly common.

The `deepsig:data_size` field is inconvenient (and in Bytes... the offset needed to be in bytes so we did that for this one also), and I strongly agree with the principle you outlined.... **however** some files (_cough*cough_ MIDAS) also have extended variable-length header fields that follow the data segment so you can't trust just `file_len - data_offset`.

I think that what you propose is a good start and covers many use cases, and if these offsets are required  can always be solved like we did (in extensions).
