### ISSUE TITLE
Bug in Validator/Schema

### ISSUE THREAD

**Issue by Teque5** [gnuradio/SigMF#174]
We need a PR to fix a few small issues and the schema.

1. The validator makes a distinction between "sections" and "keys" and there really isn't any difference. As written the validator will fail on any key with a `list` type. We have `dict_list` and `double_list` now so we should fix this. Most conspicuously it prevents proper use of the `core:extensions` field.
2. When the `collections` PR was merged it left some comma errors in the schema.
3. The top-level key sorter in `sigmffile.py` should have `collection` added.

My coworker is going to write up a PR for this, since it prevents normal use of the "core:extensions" passing the `sigmf_validator`.

**Comment by bhilburn** [comment]
Marking for v1.0.0

**Comment by jacobagilbert** [comment]
Resolved with the merge of #224
