### ISSUE TITLE
Creating a SigMFFile object without optional fields fails

### ISSUE THREAD

**Issue by jacobagilbert** [gnuradio/SigMF#178]
The `global_info` parameter is optional to `SigMFFile`, but parsing will fail without this. Specifically, the `DATATYPE_KEY = "core:datatype"` field is required. While it is required for a valid SigMF metadata file, its possible that it would be added later by a user. If the global_info field is required, it should probably be required.

to reproduce:
```python
import datetime as dt
from sigmf import SigMFFile
import numpy as np

data = np.zeros(1024, dtype=np.complex64)
data.tofile('/tmp/example.sigmf-data')
meta = SigMFFile(
    data_file='/tmp/example.sigmf-data'
)
```
result:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/SigMF/sigmf/sigmffile.py", line 97, in __init__
    self._count_samples()
  File "/opt/SigMF/sigmf/sigmffile.py", line 278, in _count_samples
    sample_size = self.get_sample_size() # size of a sample in bytes
  File "/opt/SigMF/sigmf/sigmffile.py", line 261, in get_sample_size
    return dtype_info(self.get_global_field(self.DATATYPE_KEY))['sample_size']
  File "/opt/SigMF/sigmf/sigmffile.py", line 487, in dtype_info
    dtype = datatype.lower()
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by jacobagilbert** [comment]
@Teque5 If you agree, this is a simple fix to the `SigMFFile` constructor:

```python
def __init__(self, *, global_info, metadata=None, data_file=None, skip_checksum=False):
```

**Comment by Teque5** [comment]
I see your point. Since there is no obvious way to infer the datatype I guess `global_info` should be required. This is an okay fix.

It would be possible to *guess* the datatype based on a spectral analysis but we should probably avoid that.

**Comment by jacobagilbert** [comment]
While datatype inference can be remarkably effective, I don't think it has any place in a specification. Will PR this to make it required.
