### ISSUE TITLE
Have only one way to write little-endian

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#18]
I was asked to review the SigMF specification by @bhilburn. It currently says:

> All of these must be explicitly specified, except for endianness which is assumed to be little-endian unless specified otherwise.
>
> ...
> 
> `<r|c>``<f|i|u>``<8|16|32>``[<_le|_be>]`

This seems like a pointless degree of freedom, which creates the opportunity for confusion such as taking no-suffix as meaning platform native or big endianness, particularly if an implementor works from examples rather than spec.

I suggest making `<_le|_be>` non-optional. (Also fix the markup that is showing <code>`</code> characters here while you're at it.)

**Comment by bhilburn** [comment]
Hm, yeah, that markdown is broken.

Regardless, it's a fair point. I believe we originally did this in an effort to keep things as simple as possible, but I agree it does open the door to confusion where we could easily avoid it.

I'm on-board with the change. Opinions from anyone else?

**Comment by bhilburn** [comment]
Okay, PR is up at #33!

**Comment by bhilburn** [comment]
Closed per #33's merge.
