### ISSUE TITLE
Collection Schema Breaks Things

### ISSUE THREAD

**Issue by Teque5** [gnuradio/SigMF#181]
Okay so since the collection PR was merged all the tests fail since in the default `sigmffile()` we use the `schema.json` to define a set of default metadata keys based on the schema (in `get_default_metadata()`). 

We have two options to fix this:

1. Just specifically exclude the "collection" key from the schema when importing and have the schema file hold (2) separate schemas - for `sigmf-meta` and `sigmf-collection`.
2. Split the schema into `schema-meta` and `schema-collection`.

I prefer option 2 since it's simpler.

**Comment by jacobagilbert** [comment]
Might make more sense to explicitly include the appropriate keys from schema.json; as this grows its possible another top level object could make it in there.

**Comment by jacobagilbert** [comment]
@Teque5 i rebased this with the fixes you made; how are you running the SigMF test code? It would be good to add a test that catches this error.

**Comment by Teque5** [comment]
@jacobagilbert to test just go to the root of `SigMF/` and type `pytest .` or sometimes I do `python3 setup.py test`.
