### ISSUE TITLE
Add a section defining "compliance"

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#189]
Right now, the definition of  "compliance" is kind of spread throughout the spec. Should make a section specifically for it.

**Comment by jacobagilbert** [comment]
I think this is a good idea.

IMO There are two aspects of "compliance": datasets and applications.

Datasets are "compliant" by containing **all required** `core` SigMF fields (as well as all required fields from any named extensions in the `global` `extensions` field). Optional fields may also be included (obviously) but there is no requirement based around optional fields. Datasets cannot be "compliant" if they contain **any** fields which are not defined in the specified namespace.

There are applications implementing SigMF for one or more ICDs, which are "compliant" by supporting **all required** `core` SigMF fields (as well as all required fields from any supported extensions) and a documented list of optional `core` SigMF fields (as well as a documented list of optional fields from any supported extensions). Applications which handle illegal (not defined in the specified namespace) fields _can_ be compliant, but the corresponding datasets with these fields are not.

My $0.02.
