### ISSUE TITLE
Consider Support for Double Precision Floats

### ISSUE THREAD

**Issue by jacobagilbert** [gnuradio/SigMF#196]
Per use case outlined here https://github.com/miek/inspectrum/pull/206 we may want to support f64 (and cf64?) aka double precision float data.

Thanks @777arc

**Comment by jsallay** [comment]
I would vote for inclusion of double precision data for a variety of reasons.  First and foremost, VITA49 supports double precision data.  The more interoperability between SigMF and VITA49 the better.  As noted in the linked issue, double precision is the standard for floating point data in a lot of fields and in a lot of software.  Including double precision makes SigMF a more friendly format for beginners and increases its utility.  

A collection can contain multiple files, and it is my understanding that not all of the files need contain RF data.  For example, I could have a SigMF recording containing antenna pointing or other regularly sampled information.  Double precision could be needed for certain types of data.

**Comment by jacobagilbert** [comment]
See #197 for an additional reason to include this.

**Comment by jacobagilbert** [comment]
Closed by inclusion of feature in #228, thanks @gmabey!
