### ISSUE TITLE
Example of file write uses an unsupported type cf64_le

### ISSUE THREAD

**Issue by sandersa-nist** [gnuradio/SigMF#197]
When running the example for data storage on the readme.md page, there is an error 

data = np.zeros(1024, dtype=np.complex64) uses an unsupported type in sigmffile.SigMFFile the code around line 554 needs to be updated to include  
    if "64" in dtype:
        sample_size = 8

**Comment by jacobagilbert** [comment]
Thanks for the report @sandersa-nist - currently `64` types are not supported, and there is an open issue to include support for these (#196) so I'm going to close this as a duplicate to that. If you'd like to explain your use case there it will put more pressure on us to get that supported :)
