### ISSUE TITLE
Points of clarification on NCD

### ISSUE THREAD

**Issue by gmabey** [gnuradio/SigMF#219]
Since `core:datatype` is a required keyword under `global`, it seems to me that there ought to be some standard way to indicate that the data is NCD, and that the spec should reflect this way (whatever it's determined to be).

I hereby suggest that in the case of NCD, that `core:datatype` be required to map to the string `"NCD"` (I know, it's innovative) and that this become a new allowed value in the `### SigMF Dataset Format` section.  The user would then be expected to include other user-defined fields to convey the datatype/structure in use (still respecting `trailing_bytes` and `header_bytes` of course).

The alternative (which I dislike) is to make the `global:datatype` field OPTIONAL, and when absent, that either `dataset` be non-empty or that `metadata_only` be asserted ...

**Comment by jacobagilbert** [comment]
We cannot overload the datatype field in this way as this field is often used in parsing non-compliant datasets. If none of the datatypes in SigMF effectively describe the dataset, it would be up to the end application to add an extension to add support, or perhaps SigMF is not appropriate.

We intentionally do not explicitly define whether a dataset is compliant or not, as this presents opportunity for conflicting data. Its easy to check for compliance
- The `trailing_bytes` and all `header_bytes` fields must not be used (or all be zero)
- the `core:dataset` field must not be used (or be set to `METAFILE_BASE_NAME.sigmf-data`)

**Comment by gmabey** [comment]
Ok, that all makes sense -- thanks for the explanation.

And, the interested reader will find that the `SigMFFile._is_conforming_dataset()` method is pretty close to the check that @jacobagilbert described.
