### ISSUE TITLE
Clarify what bitwidth means for complex samples

### ISSUE THREAD

**Issue by apcragg** [gnuradio/SigMF#231]
There is some ambiguity in the documentation regarding complex sample bit-widths. Numpy treats the total sample bit-width as the sum of the widths of both I and Q samples. SigMF treats the bit-width field as the width of a single component of a complex number. This could be clarified in the documentation given that it diverges from the most popular python numeric library. I actually prefer the SigMF style and it's how I've heard it referred to all over industry but it still could be a point of confusion.

Example:
True Behavior
```
cf32_le ===> { [    I0    ], [    Q0    ], [    I1    ], [    Q1    ], [    I2    ], [    Q2    ] ... }
                   32-bit        32-bit       32-bit         32-bit       32-bit       32-bit
                  ^----64-bit total---^
```

Numpy Consistent Behavior
```
cf32_le ===> { [    I0    ], [    Q0    ], [    I1    ], [    Q1    ], [    I2    ], [    Q2    ] ... }
                  16-bit        16-bit       16-bit         16-bit       16-bit       16-bit
                  ^----32-bit total---^
```

**Comment by jacobagilbert** [comment]
Hi @apcragg thanks for issue. The spec _is_ pretty specific already:

> the string "cf32_le" specifies "complex 32-bit floating-point samples stored in little-endian", the string "ru16_be" specifies "real unsigned 16-bit samples stored in big-endian", and the string "cu8" specifies "complex unsigned byte".

Numpy is a bit obnoxious (and has the quirk you also identified in #226 recently which was just fixed) in that it does not follow the strong convention for datatype nomenclature. Can you take a look at #232 and tell me if this note would have helped you?

**Comment by apcragg** [comment]
Hey Jacob thanks for the quick response. That perfectly clarifies it from my perspective. Thanks!

**Comment by gmabey** [comment]
I'm starting to think that this kind of clarification could/should go into a FAQ page instead of into the standard itself. Likewise for #220
