### ISSUE TITLE
Clarify the purpose of `latitude` and `longitude`

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#24]
`core:latitude` and `core:longitude` are specified as properties of annotation objects. It is not at all clear what these are supposed to mean; the specification notes that a standard for their representation is needed, but one is also needed for the _meaning of having coordinates here at all_.

A possible interpretation is the location of a transmitter whose signal is seen in this portion of the recording. But for that to be useful, surely the location of the receiver is also needed. If these properties are intended to be of the receiver, then why are they not _segment_ properties instead of annotation properties?

Secondary things:

* I would suggest, rather than having separate `latitude` and `longitude` properties, defining an object type containing them. This also allows later defining fields for altitude (which can be recorded with regard to several different references), orientation (relevant to antenna properties), velocity (Doppler shift, location interpolation), et cetera, without needing to repeat these concepts wherever such might be used by future extensions.

* A good answer for the question about type is "number, degrees north and east in WGS84 coordinates". This is the most common representation and most likely to not require an awkward conversion.

**Comment by bhilburn** [comment]
Excellent point, @kpreid, and as you said in the other thread, I think this is tightly coupled with #4.

Actually, I'm going to move this entire conversation back over there and amalgamate some of the points being made.
