### ISSUE TITLE
Release new version of SigMF (especially on pip)

### ISSUE THREAD

**Issue by mattpopovich** [gnuradio/SigMF#246]
First night of diving into this project, but wanted to point something out. 

I installed via `pip install sigmf`, no issues, which installed `sigmf.__version__ == '1.0.0'`. The issue arose when trying to run the sample script to write a SigMF file from a numpy array [from the README](https://github.com/gnuradio/SigMF#write-a-sigmf-file-from-a-numpy-array). 
```console
root@ubuntu:/workspace# python3 -i example.py 
\Traceback (most recent call last):
  File "/workspace/example.py", line 14, in <module>
    meta = SigMFFile(
  File "/usr/local/lib/python3.10/dist-packages/sigmf/sigmffile.py", line 120, in __init__
    self.set_data_file(data_file, skip_checksum=skip_checksum)
  File "/usr/local/lib/python3.10/dist-packages/sigmf/sigmffile.py", line 389, in set_data_file
    self._count_samples()
  File "/usr/local/lib/python3.10/dist-packages/sigmf/sigmffile.py", line 355, in _count_samples
    sample_size = self.get_sample_size() # size of a sample in bytes
  File "/usr/local/lib/python3.10/dist-packages/sigmf/sigmffile.py", line 337, in get_sample_size
    return dtype_info(self.get_global_field(self.DATATYPE_KEY))['sample_size']
  File "/usr/local/lib/python3.10/dist-packages/sigmf/sigmffile.py", line 629, in dtype_info
    raise SigMFFileError("Unrecognized datatype: '{}'".format(dtype))
sigmf.error.SigMFFileError: Unrecognized datatype: 'cf64'
>>> get_data_type_str(data)
'cf64_le'
>>> sigmf.__version__
'1.0.0'
```

However, when I built from source and ran the same file, no errors:
```console
root@ubuntu:/workspace# python3 -i example.py 
>>> get_data_type_str(data) 
'cf32_le'
>>> sigmf.__version__
'1.0.1'
```

This has already been identified in #226 and then fixed in #228 and clarified in #232. 

Seems like a pretty major change to consider two single-precision floating-point numbers a `cf64` in one release and a `cf32` in another, although it seems like SigMF has always *considered* them `cf32`, it was just a bug in `get_data_type_str()`...

### Solution
Release v1.0.1 on pip so that users that install SigMF via pip can run the examples in the README.

Note that the code in the README of master branch is the same as sigmf-v1.x branch and does not work on v1.0.0 either. So it's not like something broke in v1.x. More like the README wasn't working in v1.0.0 and v1.x fixed it.

**Comment by mattpopovich** [comment]
In the meantime, SigMF tags/commits [can still be installed from pip](https://stackoverflow.com/a/13754517/4368898). Ex
```console
# pip install git+https://github.com/gnuradio/SigMF.git@SigMF-v1.0.1
# pip install git+https://github.com/gnuradio/SigMF.git@92b0ffb36a16f8a69a42248833710e365e42e96f
```

**Comment by mattpopovich** [comment]
Would be nice if the releases on GitHub matched the releases on PyPI... Although it seems as if the tags match better.

| [GitHub Releases](https://github.com/sigmf/SigMF/releases) | [GitHub Tags](https://github.com/sigmf/SigMF/tags) | [PyPI](https://pypi.org/project/SigMF/#history) | 
|------------------------------|---|--------|
|                                   | v1.1.0: Jan 16, 2023 | v1.1.0: Jan 16, 2023 |
|                                  | v1.0.1: Dec 13, 2022 |        |
| v1.0.0: Jan 6, 2022   | v1.0.0: Jan 5, 2022 | v1.0.0: Jan 27, 2022 |
| v0.0.1: July 17, 2018 | v0.0.1: July 17, 2018 | v0.0.1: Oct 2, 2017 |
|                                   |  | v0.0.0: Oct 2, 2017 |

Would it be useful if I/someone made a PR to enable GitHub actions to automatically make GitHub releases/tags into a package and push it to PyPI?

**Comment by bhilburn** [comment]
> It appears @bhilburn and/or @jacobagilbert owns [the project](https://pypi.org/project/SigMF/) on PyPi, but if one of you adds me as a "collaborator" I can push new releases. I do this for two other projects.

Happy to, @Teque5 -- what's your associated username / e-mail?

**Comment by Teque5** [comment]
> Happy to, @Teque5 -- what's your associated username / e-mail?
Sry, identical to my name here: Teque5

**Comment by bhilburn** [comment]
@Teque5 - Done!

![image](https://github.com/sigmf/SigMF/assets/569571/9ff599b2-fda3-4645-9d26-65579c5ba58d)

**Comment by mattpopovich** [comment]
@Teque5 Ok, but what is the codebase commit for that release? What are the differences between v1.1.0 and v1.1.1? I don't see any tags or releases on GitHub marked as v1.1.1.

Actually, I've just realized that the Python module has moved to [its own repo](https://github.com/sigmf/sigmf-python) as of 7f05cc98a239b0fca63598eda07f1d510ea7fad7 and that this repo is now just the SigMF specification. I see no tags or releases at [sigmf-python](https://github.com/sigmf/sigmf-python) as well.
