### ISSUE TITLE
Make license information machine-readable when possible

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#25]
If the license information is not, or not exclusively, free-form text (with potentially many variations on references to a single license) but contains some kind of formally specified reference to the license, then it is possible for automated systems to determine whether they can process a dataset without violating its license.

An archive of datasets might want to display publicly only datasets with compatible attribution requirements, or allow searching with license as a criterion.

The results of such a search could be used as input to some process which combines many datasets (machine learning, distributed receivers, propagation analysis…), producing a derived work without any person needing to evaluate the individual inputs.

#20 may be relevant; I'm sure there are already-existent vocabularies for license metadata but I am not familiar with anything in specific.

**Comment by mbr0wn** [comment]
Yeah, this is worth investigating.

**Comment by bhilburn** [comment]
This is a really good point, although I'm not terribly sure how to proceed.

Perhaps, for now, we can just add a recommendation of this to the spec regarding the license field. Unless anyone has good ideas, here, I'll proceed with that plan.

**Comment by kpreid** [comment]
A simple from-scratch strategy might be "must be a URL for the license document; when possible, one defined by the license author rather than specific to this dataset".

**Comment by bhilburn** [comment]
Okay, #54 is up for this!

**Comment by bhilburn** [comment]
Fixed by merge of #54!
