### ISSUE TITLE
Clarify what `core:offset` is good for

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#26]
`core:offset` is specified to be “The index number of the first sample in the dataset. This value defaults to zero.”

Within the elements of the specification, it seems to have no effect whatsoever if I take some dataset and add/subtract the same value from all occurrences of `core:offset` and `core:sample_start`.

Therefore, it is either unnecessary complexity and should be removed, it is meant to have some possible meaning beyond the scope of one dataset which should be explained, or it has some other role that is not sufficiently explained.

**Comment by mbr0wn** [comment]
The main purpose of `core:offset` is the case where a recording is split over multiple files. If the first file has 1000 samples, and the second has the next 1000 samples, the second will also have a `core:offset` of 1000.

**Comment by mbr0wn** [comment]
#27.

**Comment by kpreid** [comment]
That seems reasonable. I feel like there's some clarification that ought to be made (along the lines of "applications should not assume that core:offset means anything in particular other than how sample indexes should be displayed/accepted for reference by users" but more objectively defined) but I can't think of it at the moment.

**Comment by bhilburn** [comment]
Merged #27!
