### ISSUE TITLE
is anyone else interested in a `core:uuid`

### ISSUE THREAD

**Issue by gmabey** [gnuradio/SigMF#267]
To each of our annotations we assign a UUID; it helps us keep track of things when they get pushed into a database like ElasticSearch.

This issue is just a probe to test whether anyone *else* would find a new `core:uuid` tag to be interesting/useful; just thumbs-up or thumbs-down on this message to vote (I guess).

**Comment by jacobagilbert** [comment]
Thats interesting, we have a `deepsig:uuid` field that we use as well...
