### ISSUE TITLE
Annotate frequency but not time

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#29]
Annotations require bounds in time/samples and have optional bounds in frequency. Might it be useful to allow annotations with bounds in frequency but not in time?

For example, in a recording that is known to be of a transmission (or several) whose carrier frequency is not the center frequency of the recording, to mark the carrier frequency and/or band edges.

Obviously one can create an annotation whose sample range extends from the beginning to the end of the recording, but applications could benefit from knowing that it's not a thing that _happens_ to start/end there but is actually timeless.

**Comment by smunaut** [comment]
+1 to that

**Comment by bhilburn** [comment]
Good idea, @kpreid.

I'm trying to sort out the best way to enable this without making the `annotation` segment spec too confusing. We could just make `sample_count` optional, where if it's not specified it applies to the entire capture?

**Comment by kpreid** [comment]
You mean also making `sample_start` optional, right? Or that writers would set it to 0?

How about using `sample_end` instead of `sample_count`, so that we have in general an absolute-coordinates “rectangle” of time/frequency space where any of its four sides can be “out at infinity” as suits the application.

**Comment by bhilburn** [comment]
So the way I'm thinking about this, `sample_start` is always required. In the case you gave in the initial post, it would be index `0`. What would be optional would be when it ends.

We actually chose `sample_count` instead of `sample_end` for a reason in Brussels... and I'm having trouble remembering why, now, unfortunately. Do you have any recollection, @smunaut, @mbr0wn, or @jarn0ld?

**Comment by bhilburn** [comment]
So, I think the best way to handle this is simply to use the `sample_start` field, set to 0, and make the `sample_count` field optional. If the latter is empty, then the annotation applies to the entire recording. That enables you to describe something in frequency without specifying time bounds.

Thoughts?

**Comment by mbr0wn** [comment]
I can remember we had a discussion of count vs. end, but I'm not sure what it was. We actually started with end, and then switched to count for what was probably a very good reason.

**Comment by mbr0wn** [comment]
I think using count just makes it a lot easier to move segments around, reorder them, etc.

**Comment by bhilburn** [comment]
Okay, so is everyone on-board with this? Basically, the spec would say:

"`sample_start` is always required. If `sample_count` is provided, that is the number of samples that the annotation applies to. If `sample_count` is ommitted, the annotation applies from `sample_start` to the end of the recording."

**Comment by bhilburn** [comment]
This is an easy change, and a low burden to applications. Adding this to v0.0.2.

**Comment by bhilburn** [comment]
Easy fix that I believe preserves backwards compatibility. Marking for v1.0.0.

**Comment by gmabey** [comment]
@bhilburn Any feedback on the PR?

**Comment by bhilburn** [comment]
@gmabey - Same as the other one, I've approved it, but it would be great to get a 2nd reviewer on it. Can you take a pass on it and either leave comments or approve?
