### ISSUE TITLE
Metadata Streaming

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#36]
In a thread on the `gnuradio-discuss` mailing list, @bastibl raised what I think is a fair criticism of SigMF:

If the `capture` parameters are changing at all, then writing a SigMF metadata file can't be done in a purely streaming fashion. If you start a capture, write that first `capture` segment, and then start streaming `annotations` to disk, as soon as you need to update the `capture` parameters you need to stop streaming, hop back in the file, write the new segment, and hop back to the end before you can continue streaming annotations. 

How serious of a problem is this? In the event where a new `capture` segment is needed pretty regularly, it could cut down pretty heavily on performance.

At the hackfest where SigMF work first began, we made the explicit decision **not** to intermix the `capture` and `annotation` segments so that you wouldn't have to search over every metadata segment to find the one that's relevant to wherever you are in the datafile. Now that we have ~2 months of discussing, debating, and building on the spec, does this still look like the best decision?

Since the spec doesn't place any requirement that the metadata file has to be written all-at-once, it seems like the recording application could simply stream two files in parallel, one for `capture` and one for `annotations`, and then combine them at the end. Thoughts on this?

**Comment by kpreid** [comment]
> Since the spec doesn't place any requirement that the metadata file has to be written all-at-once, 

Not only does it not, it _should_ not. That would be as silly as requiring a non-streaming writer to keep the information in some specific memory layout — it's an implementation detail that nothing else should ever see.

If the metadata were in some non-JSON format that was itself interpretable when partially written, it would make more sense to make it “directly” streamable, but generally a JSON document missing its final `}` is considered unparseable (though this of course could be done anyway).

> not to intermix the capture and annotation segments so that you wouldn't have to search over every metadata segment to find the one that's relevant to wherever you are in the datafile.

This is not a good rationale. A typical SigMF reader application will parse the JSON and then (maybe) convert the JSON into some internal representation. That's at least one pass over the entire dataset, which is a fine opportunity to separate capture segments from annotation segments if you care — or do _anything else to reorganize the data in a useful fashion._

If this is the only reason you have to not mix, then it would make more sense to mix and allow naïve streaming writers. (But that would require each segment to say whether it is a capture segment or annotation segment, and possibly cause implementors to think they are more similar to each other than they are, so I don't actually propose this.)

**Comment by ctriant** [comment]
> If the capture parameters are changing at all, then writing a SigMF metadata file can't be done in a purely streaming fashion. If you start a capture, write that first capture segment, and then start streaming annotations to disk, as soon as you need to update the capture parameters you need to stop streaming, hop back in the file, write the new segment, and hop back to the end before you can continue streaming annotations.

As far as I understand the specification, there is a 1-to-N relationship between capture and annotation segments. Thus, wouldn't be an idea to inject the annotation segments inside capture segments? 
That way, by the time that no more annotations are needed for a specific capture segment, this segment is considered fulfilled and is added to the capture segments' list.

**Comment by kpreid** [comment]
> As far as I understand the specification, there is a 1-to-N relationship between capture and annotation segments.

It's not a 1-to-N relationship, because an annotation segment could span multiple capture segments. We could specify that annotations are placed with the capture segment containing their _end_ point but I think if we entangle these things then just allowing them to be mixed in the list makes more sense.

**Comment by bhilburn** [comment]
Okay, based on this discussion, it sounds like there is not a compelling reason to change our original design.

Realistically, a writer application could simply be streaming two files, a capture file and an annotations file, and then concatenate them to create a SigMF recording. There are a number of other ways this could be handled depending on the requirements of the application.

Does anyone have further comments on this, either in support or opposition to the current design?

**Comment by bhilburn** [comment]
Since we have no further disagreement on this issue, I'm closing it.
