### ISSUE TITLE
Specify Floating-Point Standard

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#5]
Comment from reviewer:

> Note that the current SigMF does not specify -which- floating point format to use. For 32 bit, IEEE-754 would seem sensible, and presumably the half-precision format from IEEE754-2008 ?

It's a good point. Agree / disagree with the suggestion?

**Comment by smunaut** [comment]
I didn't remember we spec'd support for half-float at all ..

IEEE-754 makes sense, but I'm wondering if we shouldn't allow for undefined behavior for non-finite values and non-normalized ones. After all we expect physical values here and using -ffast-math makes sense a lot of the time. Just a thought ...

**Comment by bhilburn** [comment]
@smunaut raises an interesting point. Technically, as our datatypes are defined, someone could actually use `cf8` and it would be valid. This is item `#1`.

Item `#2` is @smunaut's point about finite/normalized values. Thoughts, here? Guaranteeing compatibility with things like `--ffast-math` is nice, but is that moving too far in the direction of recommended toolflows? Do we preclude other tools by *not* allowing for non-finite/non-normalized values?

**Comment by bhilburn** [comment]
Okay, so, fixing this is going to require a change to the general format of the `datatype` section, as we need to limit the floating-point options.

Proposal: we only allow single-precision IEEE 754 floating point (32-bit floats) samples, and do not allow for half-precision (16-bit floats).

Question: Should we add double-precision to the standard? I'm leaning towards `no`, as that may become a burden to becoming `SigMF Compliant`. This could be done through an extension, instead. Thoughts?

Question: I would like to get some more input on @smunaut's point on finite/normalized values.

**Comment by bhilburn** [comment]
Unless anyone has further input on my question, above, I'm going to move forward with the proposal as I stated it.

**Comment by bhilburn** [comment]
Okay, #43 is up for this.

**Comment by bhilburn** [comment]
Closing this as the discussion has moved to #43.
