### ISSUE TITLE
Multiple recordings per archive

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#50]
In #44, we raised the idea of including multiple recordings in a single `sigmf` archive.

[Recall that we define a `recording` as a single pair of dataset & metadata files, per this line in the spec: https://github.com/gnuradio/SigMF/blob/master/sigmf-spec.md#files]

@kpreid raised the following point about allowing for multiple recordings in an archive:

> It is a UI/API complication for anything that wants to read a SigMF recording because you then need more than a file-picker, and people will be tempted to create little languages for representing pathnames-plus-item-in-the-archive, which gets messy.

Allowing for multiple recordings per archive has the advantage that one recording could be split, but still distributed in a single archive. The current directory structure of the archive would already allow for this, as recordings must be in a sub-directory of the top-level, per #44.

Per the comment above, though, this does introduce complexity to reader applications, as they can no longer simply glob the archive and run with it, because there will be multiple recordings to choose from.

So, thoughts & input on this?

**Comment by storborg** [comment]
Filling in a bit of notes from the GRCon discussion yesterday...

One concern with this is that it introduces the possibility for certain core fields to be either contradictory or redundant. For example, could one recording specify a license that is different from another recording in the same archive? How should reader applications treat this?

Also, would multiple recordings be allowed only in .tar files, or with individual files as well? It might be tricky to write an application that can record multiple live data streams to a .tar file and still guarantee valid data in the event of a crash.

Along these lines, I think if SigMF were to allow multi-channel recordings, it would be helpful to define separate terminology for "the collection" vs "the channel" and stick with it. Using the term "archive" may be confusing for this if multiple sample streams are allowed in either tar files or individual files.

**Comment by bhilburn** [comment]
Thanks for providing input from the GRCon discussions, @storborg!

In reviewing the spec that we had, it became pretty clear that multiple recordings per archive actually wasn't prohibited by the spec, it just wasn't called out. Our usage of the words "archive" and "recording" was also fairly confusing, to be honest. I just yesterday pushed a change to the spec that clarified the usage (as in, uses them consistently), and also added a line that specifically says multiple recordings can be included in an archive (which, previously, was only implicitly allowed).

So, now that the spec isn't so confusing to read with respect to the multiple recording question, let's talk about whether or not this makes sense. @storborg raises a really good point about conflicting information between recordings. What if someone amalgamates different recordings with different licenses into an archive? How problematic is that?

In my opinion, we absolutely need to have multiple-recordings-per-archive to support multiple channels, per #19. But we do need to write it in a way that makes sense. Some topics for discussion:

1) Should we have a top-level metadata  file, unattached to a dataset file, but that describes an archive?
2) Should we introduce a new term (e.g., `collection`) and clarify that an `archive` is simply a single bundled `recording`? Or should we keep the existing spec where an `archive` can have multiple `recordings`? This is a really a question of what is most clear and easy to understand.
3) Should we try to resolve the problem of conflicting fields across recordings?

**Comment by bhilburn** [comment]
Fixed by merge of #85
