### ISSUE TITLE
Volatile Fields

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#55]
In #4, the issue of fields that are continuously changing came up:

> So, I think this raises an important question, which is how do we best deal with changing values for any of these fields? What if the antenna is being rotated during the capture to sweep an area (e.g., RADAR). What if the receiver is moving, and so the long/lat fields are changing rapidly?
> 
> Generating a new capture segment for every change would result in a new capture segment for every single sample, which is obviously incredibly cumbersome.

@kpreid threw in the idea of:
> One could add angular velocity fields so that the application can interpolate. That would still require multiple segments to approximate reality, because any given interpolation strategy does not reflect the actual axes of rotation of the antenna rotator or whatever, but it might make the required volume of data more reasonable.

And @patchvonbraun added:
> I'm thinking that there's no clear "best way" to handle these
> situations.  For example, the application could clearly decide for
> itself what granularity to update some types of metadata, which implies
> that "carry over" would be acceptable.
> 
> If one considers, from the radio astronomy perspective, an antenna that
> is tracking a source, it could reasonably want to update az/el
> information on a "routine basis", but certainly not on an
> every-damned-sample basis.
> 
> I wonder if there's guidance on these types of issues from existing
> standards?  Like the FITS standard that is used in science for various
> types of annotated,
>    vaguely image-like, data?

I think this is an important issue to discuss and address to whatever degree we are able.

What if we were to define an ancillary field that defined movement in a generic and standard way in a canonical namespace that could be attached to other fields (like location, antenna, etc.,)?

The hardest part of this, obviously, is "how do you define movement in a standard way" - is anyone aware of an existing standard for this that we could leverage?

**Comment by Vinz87** [comment]
In my opinion, metadata don't change over a dataset, generally speaking.

If the radar's antenna rotates over the acquisition, the antenna pointing is not a metadata anymore, it's another time-varying piece of information, another signal to be sampled, i.e. another dataset.

If the location of the platform changes because it is moving, it stops to be a metadata and it will become another dataset. Also keep in mind that a GPS position is logged at a typically lower rate than the physical measurement of the sensor. Therefore, different rates issues or interpolation needs would come up if thought as a metadata.

**Comment by kpreid** [comment]
That is an interesting angle on the problem and might produce some good ideas.

My first reaction was that parameters in a recording from a manually controlled station might change infrequently (e.g. antenna rotation, center frequency), so a recording at a fixed sample rate does not make sense — it is either too fine most of the time, too coarse when the event actually happens (some but not all retuning events benefit from to-the-sample time precision; antenna pointing might want enough data to follow the rotation and not just the final position), or both.

On the other hand, for many applications a reasonable sample rate would be an utterly insignificant amount of data compared to the actual signal recording.

**Comment by bhilburn** [comment]
Wow, @Vinz87, that is a really, really interesting perspective. Frankly, it's the first suggestion I've heard about how to think about this that doesn't seem like an overwhelming metadata problem, hah.

So, building this idea out a bit further, we could take advantage of the multiple recordings per archive discussion (#50) to specify a way to package recordings of different types (e.g., sampled signal, a dynamic location, a dynamic antenna azimuth) to create a more complete SigMF recording. Users that cared about the location and/or azimuth could load those files, and users who didn't could ignore them. They could be recorded using the exact same spec (SigMF), but perhaps with the use of official extension namespaces (per # 13) for things like location, antenna, etc.,

Thoughts?

**Comment by bhilburn** [comment]
If everyone is on-board with @Vinz87's proposal, I'm going to roll ahead with trying to implement it in the spec. I really, really like this approach.

**Comment by djanderson** [comment]
I like the idea as well, but what are you proposing to add/remove from the
spec besides multi-recording archives?

**Comment by bhilburn** [comment]
Well, for example, we'll also need a way to indicate some relative synchronization point between two recordings (e.g., pointing to a starting sample index). I'm assuming there will be other small items like that as we start hammering the idea out.

**Comment by bhilburn** [comment]
So while thinking about and responding to #69, a thought occurred to me: we've decided that continuously variable fields are an important feature for SigMF, but is it something we want to put in the `core` namespace?

Maybe this would be better in a canonical extension namespace. That way, it's still possible to implement dead-simple compliant Reader applications, and those apps that are interested in supporting this can simply implement support for that extension.

Thoughts?

**Comment by bhilburn** [comment]
Focusing work & discussion in #99
