### ISSUE TITLE
annotations vs annotation, captures vs capture

### ISSUE THREAD

**Issue by djanderson** [gnuradio/SigMF#56]
The spec as currently written says 

> The `capture` value is an array of _capture segment objects_

and

> The `annotation` value is an array of _annotation segment objects_

However, the examples and schema appear to use the key `annotations` instead of `annotation`.

https://github.com/gnuradio/SigMF/blob/master/example_metadata.py#L26
https://github.com/gnuradio/SigMF/blob/master/sigmf/schema.json#L84

First thought: capture and annotation should either both be singular or both be plural. Let me know which it is and I'll do a pull request.

I actually like plural better since they are arrays of those objects. For example, I think:

> `annotations` is an array of _annotation segment objects_

reads better than

> `annotation` is an array of _annotation segment objects_

but either way.

**Comment by kpreid** [comment]
FWIW, I have already [said in #35 that I think they should be plural](https://github.com/gnuradio/SigMF/issues/35#issuecomment-303485097). That the examples agree is even better!

**Comment by bhilburn** [comment]
Hey @djanderson - Agreed! Yes, let's make them plural. If you want to submit a PR, I'll get it merged ASAP (I promise! ;) ).

Thanks so much for raising this `=)`

**Comment by bhilburn** [comment]
Fixed by the merge of #59!
