### ISSUE TITLE
Is anyone working on a MATLAB application?

### ISSUE THREAD

**Issue by Vinz87** [gnuradio/SigMF#58]
I would love to use this standard to generate metadata in MATLAB, has anyone started writing an application even if at this early stage?

**Comment by mbr0wn** [comment]
That's a fantastic idea -- would you want to take on this task? We would have to keep it Octave-compatible for testability reasons, but it would be a great addition to SigMF.

**Comment by Vinz87** [comment]
will try in spare time ;)

**Comment by bhilburn** [comment]
Hey @Vinz87! Let us know if you have any questions about this! Once you have MATLAB code, by the way, it would be great to discuss getting it upstreamed =)

I'm going to close this issue just to clean things up, but I would really love to see this happen. Feel free to email me `bhilburn@gmail.com` if you want to talk about anything in further detail!
