### ISSUE TITLE
Annotations: Source is computer or human?

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#6]
Paraphrased feedback I got here at DARPA's Battle of the ModRecs at DySPAN:

> It would be good to include a field in the annotation segments that define whether or not the segment was created by a program or a human. Right now it looks like people would just use the `comment` name/value for this, but you risk a "sub-standard" being created within that `comment` field since it's so wide-open.

We could do this by adding something to the `core` namespace like `author` or `source-type`, for example.

Thoughts on this idea / concern? In a situation where many different people / groups are producing annotations for the same data set, which they then share, this could be useful.

**Comment by smunaut** [comment]
Seem a bit application specific to me ... typically something they could just handle with an extension.

Just my 2ct.

**Comment by mbr0wn** [comment]
What does that even mean, "created by a human"? Is it really fundamentally different if a human triggers a record script, or another script does?

**Comment by bhilburn** [comment]
I think it is worthwhile to be able to distinguish the source of an annotation, especially in scenarios where multiple entities are adding annotations - something we want to enable with SigMF.

Proposal: We add an `optional` field to the `core` namespace, to be used in `annotation` segment, called `reporter`, that allows the entity making the annotation to enter an appropriate label. 

Thoughts?

**Comment by bastibl** [comment]
reminds me of the HTML `<meta name="generator" ..>` tag. How about `generator`?

**Comment by bhilburn** [comment]
I like @bastibl's suggestion of `generator`, and have submitted a PR for it (#30).

Please review!
