### ISSUE TITLE
Incorrect tar format in python code

### ISSUE THREAD

**Issue by pwicks86** [gnuradio/SigMF#61]
The python code creating sigmf archives in this repository uses the wrong format for it's sigmf files. The spec specifies that archives must be in  POSIX.1-2001 format. By default, the python tarfile module creates GNU tar files, not  POSIX.1-2001. [Line 78 of archive.py](https://github.com/gnuradio/SigMF/blob/master/sigmf/archive.py#L78) should be `sigmf_archive = tarfile.TarFile(mode="w", fileobj=sigmf_fileobj, format=tarfile.PAX_FORMAT)`

I can provide a PR for this as well, but it's a pretty tiny change

**Comment by djanderson** [comment]
@bhilburn, feel free to assign me. I'll add a test for the format as well.

**Comment by bhilburn** [comment]
Excellent catch, @pwicks86! Thanks so much for spotting this and then raising it. Especially in standards / specifications, being pedantic to the extreme is the best way to guarantee that everyone walks away with the same understanding of the spec.

@djanderson - Sounds great! Go ahead and submit the PR whenever you're ready `=)`

**Comment by mbr0wn** [comment]
@bhilburn I've invited @djanderson to gr-devs, when he accepts, you can assign to him.

**Comment by bhilburn** [comment]
Fixed by #78. Thanks, everyone!
