### ISSUE TITLE
Make it clear that both `freq_lower_edge` and `freq_upper_edge` are required if one is present

### ISSUE THREAD

**Issue by schneider42** [gnuradio/SigMF#71]
The spec says that `freq_lower_edge` and `freq_upper_edge` are not required to describe an annotation.

It is therefore possible to only specify one of them inside an annotation. Is this intended?

The same applies to latitude and longitude.

**Comment by bhilburn** [comment]
@schneider42 - Excellent point. Right now, this is undefined. It seems to me that we have a few options:

1. If only one or the other is defined, then it is considered to be an end-to-index slice of the frequency. Would this be a useful feature to support?
2. If we want to disallow it, then we can either call that out as not being compliant, and/or maybe combine them into one field to make it more apparent that you can't do one without the other.

Thoughts / opinions / suggestions?

**Comment by kpreid** [comment]
Unlike the time axis, the frequency axis limits are known up-front. Remove unnecessary degrees of freedom. Require that both are present or both are absent.

(Tangent: Digital signals are circular in frequency. It arguably makes sense to allow an annotation which spans the nominal wraparound point, upper edge numerically less than lower edge, e.g. to be able to label a strong signal that got past antialiasing filters to plop itself right there. Do we want to bother? I dunno.)

**Comment by mbr0wn** [comment]
Do we have any fields that are actually vectors? JSON supports that, after all. Most of our fields are scalar values, if they're numbers, but that's just because we chose it that way. The frequency range could be a vector of 2 doubles.

**Comment by bhilburn** [comment]
@kpreid - Good point.

@mbr0wn - Hm, interesting point. By `vector` do you mean an `array` (http://www.json.org/)? We are obviously using arrays in the SigMF spec, but not quite like this, and I rather like the idea.

Basically:
```
core:frequency: [lower, upper]
```

Thoughts?

**Comment by bhilburn** [comment]
Okay, so how about we blow away `freq_upper`, `freq_lower`, move to an array, and don't put any requirements on one being more / less than the other, per @kpreid's point about wrap-arounds.

**Comment by n-west** [comment]
As discussed at grcon18 the room consensus was the practical solution is to require both frequency edges to be present

**Comment by bhilburn** [comment]
This must be resolved for v.0.0.2. The decision is clearly that either both edges are defined, or none are defined. What seems to be undecided, at the moment, is what this looks like.

I think there are two options:

* We leave it as it is now.
* We move to a JSON vector, as described in my previous comment.

Given that we have decided that one cannot exist without the other, my gut feeling is that the vector is the better approach. This, however, quite clearly breaks backwards compatibility.

So, my thinking currently is:

* For v0.0.2, add language that requires both fields.
* For v0.1.0, move to the vector format.

Happy to hear comments on this!

**Comment by schneider42** [comment]
:+1:

**Comment by n-west** [comment]
I don't think it sounds like such a great idea to use a vector format. That will break backwards compatibility entirely. I understand there's semver and all of that, but breaking compatibility for otherwise simple things (just require them both be present) means that one of two things happens:

1) Tool providers and dataset creators fork on the spec and never upgrade or don't support old versions which means new tools can't read older records
2) It is now a requirement to read and parse an entire metadata file before even discovering what fields need to be deserialized and how to deserialize them. That sounds incredibly painful.

It seems like not necessarily an issue to either require they both be present OR just leave it as open to interpretation of the application what it means when one is missing (my tools tend to reject them and issue a warning)

**Comment by n-west** [comment]
Another practical reason to not do this is that it makes code less intuitive to read and would break statically defined type hinting that can exist now.

Right now with code that reads a lower edge and an upper edge clearly say in the text "freq_edge_lower". It's pretty obvious to the reader without knowing SigMF details what is happening. With this array change that same code would now literally read "frequency[0]". What is frequency[0] to someone that happens to be reading code that isn't already intimately familiar with the spec? I think the first is far more readable

**Comment by bhilburn** [comment]
For v.1.x, spec should be updated to make it clear that *both* fields must be used together, and that one cannot be used without the other.

**Comment by gmabey** [comment]
I'm not sure I actually *recommend* this course of action, but for the sake of discussion ...
```python
...
    "freq_edges": { "lower": 3e6, "upper": 3.3e6 }
...
```
The *only* advantage (the extra structure is a disadvantage, IMHO) is that then you get to say "freq_edges is optional" ...

**Comment by jacobagilbert** [comment]
@bhilburn I think that is the only reasonable (non-breaking) course of action.

**Comment by gmabey** [comment]
@jacobagilbert Is this issue something you plan to work on this week?  If not, I could certain take a whack at it -- just adding language that replaces "optional" with "optional but must be present when `freq_upper_edge` is present".

**Comment by jacobagilbert** [comment]
@gmabey I submitted #127 for this last week.

**Comment by gmabey** [comment]
Ah, sorry my mistake --

**Comment by gmabey** [comment]
@bhilburn does @jacobagilbert 's PR look good to you?

**Comment by bhilburn** [comment]
@gmabey - I've approved it, would love to get a 2nd reviewer on it. Can you take a pass on it and either leave comments or approve?
