### ISSUE TITLE
Ability to provide only metadata for a common dataset

### ISSUE THREAD

**Issue by bhilburn** [gnuradio/SigMF#76]
This one came from the DARPA workshop at GRCon, where a number of programs / efforts plan on using SigMF.

In their particular use-cases, there is a single dataset that is common / shared with multiple parties, and everyone else is creating metadata files for that dataset that they then share. Technically, when they are shipping around these SigMF metadata files, they are "not compliant" because they aren't operating on the canonical unit of a `SigMF Recording`, which requires the presence of a dataset.

I think we are going to see this use-case become more and more common, and I think it'll be important to make it clear that it is possible to do that with SigMF. My question, then, is what is the best way to go about doing this in a way that doesn't provide room for confusion? In this use-case, the `global` and `captures` are not getting updated - it's really shipping around an `Annotations` array created by some other program. Thoughts?

**Comment by mbr0wn** [comment]
This doesn't seem like a terribly difficult problem, right? All we need to say is that partial SigMF files are still useful.

**Comment by bhilburn** [comment]
So, for some reason I had the impression that we specifically prohibited this is the spec. Looking at it, we don't. I think we're all set here!
