### ISSUE TITLE
Combine date and time values for simplicity and multi-day recordings

### ISSUE THREAD

**Issue by kpreid** [gnuradio/SigMF#8]
I was asked to review the SigMF specification by @bhilburn. It currently says:

> Global Object
>
> … `date` … An ISO-8601 formatted string of the capture date of the recording.
>
> Capture Object
>
> … `time` … An ISO-8601 formatted string indicating the timestamp of the sample index specified by `sample_start`.

I believe that this is likely to be interpreted inconsistently, and will lead to SigMF applications needing to do an unnecessary amount of “calendar” processing (which is easy to get wrong). It is not even clear to me how a recording spanning multiple days would be represented correctly.

I suggest the following change:

* Remove the `date` field from the global object entirely.
* Specify that the `time` field in segments is ISO 8601 combined date and time (as in `2017-03-15T21:11:35Z`).
* While not strictly relevant, I would also recommend requiring the use of the UTC/"Zulu" time zone.

An application wishing to have a date for the recording can simply use the date of the `time` value for the first segment.

**Comment by bastibl** [comment]
I agree that the `date` field should be removed from global and that `time` should be a combined date and time stamp.
In the example metadata file it already is
https://github.com/gnuradio/SigMF/blob/3e373892d0f022826a6b59596b2a5b7b6430135e/example_metadata.py#L19
Maybe it's just a bug in the specification.

Regarding the time zone, we could allow to set one (as in the example file) and assume UTC if none is given.

**Comment by bhilburn** [comment]
Excellent point, @kpreid, and thanks for your thoughts, @bastibl.

The `time` field in the `capture` object is indeed already `datetime`, as @bastibl pointed out, and its name is something of a misnomer.

I am actually a fan of the idea of specifying UTC Zulu. Having to deal with Daylight Savings, for example, is a complete nightmare. It's not even consistent in the USA - it's observed by all states except Arizona and Hawaii, unless you are on tribal lands in those states, in which case it is observed, and it is not observed in territories. Specifying UTC Zulu, which doesn't change, seems much simpler.

Proposal:

* Remove `date` from `global` object
* Change name of `time` in `capture` object to `datetime`
* Require UTC Zulu time

Thoughts / feedback?

**Comment by kpreid** [comment]
I was less concerned about the _name_ of the field and more about precision in what it is defined to contain. As long as the spec is not ambiguous, people will get the idea quickly from examples. I have little opinion on using `time` vs. `datetime`.

Nitpick: Even if you don't require UTC, that _doesn't_ mean you have to deal with DST, strictly speaking. DST is only an issue if you have a time zone name (commonly seen in the form like `America/New_York`) but ISO 8601 uses numeric offsets from UTC, which do not require legal-definition-of-DST rules. You still need _calendar_ information (is this a leap year, and so on) to compare times at all if they're near a day boundary, whether or not offsets are allowed, but libraries for that should be commonly available.

But specifying UTC time means that every time is represented exactly one way (outside of leap seconds), which seems like a nice property to have, though not one of obvious significant value.

**Comment by bhilburn** [comment]
Please review #31!

**Comment by bhilburn** [comment]
Discussion moved to #31.
