### ISSUE TITLE
"author" field

### ISSUE THREAD

**Issue by dharasty** [gnuradio/SigMF#80]
Greetings!  My name is Dan, and I'm just joining the SigMF discussion with this post/comment/issue.

I realize the "author" field is pretty low on the importance scale (in the grand scheme of what SigMF is for), but I have this request: let's NOT re-invent the wheel for the "author" field.

The idea of putting the author's name in the metadata is great.  But the 0.0.1 spec immediate hedges that that might not be enough, and thus adds "(and optionally e-mail address)".

As soon as you make stuff optional, you beg the questions like "If both name and email are present, what is the delimiter between them?" and "If I use the optional email, must I also include the name or can the email address stand alone?"

Here's my proposal: DON'T try to solve those questions in SigMF!

In case you are not aware, "what a contact record looks like" is possibly one of the longest simmering debates in the world of schemas.  SigMF should give deference to long standing prior work, and include it by reference.  Example: [vCard](https://tools.ietf.org/html/rfc6350) (see [RFC-6350](https://tools.ietf.org/html/rfc6350)), [jCard](https://en.wikipedia.org/wiki/VCard#jCard) (see [RFC-7095](https://tools.ietf.org/html/rfc7095)), [hCard](http://microformats.org/wiki/hcard).

One of the reasons why "what a contact record looks like" is so divisive -- and the vCard format is so complex -- is that almost every culture has a different idea for what is "obvious" when it comes to basic questions: what is the structure of a name? what is the structure of an address?  Any attempt for the SigMF team to say "let's just do a simple version of it" will be wading into a minefield of cultural debates which -- for the most part -- a [détente](https://en.wiktionary.org/wiki/d%C3%A9tente#English) has already been achieved in vCard.

If comments on this issue demonstrate a consensus that "SigMF should NOT try to define a schema for "author", then I'm happy to propose some specific language that will:
- incorporate one or more of these well-known "contact record schemas" by reference
- keep SigMF out of the "what a contact record should look like" debate
- allow the SIgMF Recording author flexibility, but also promote interoperability

Shall I draft something?

**Comment by bhilburn** [comment]
Hi @dharasty! So sorry for the delayed response, here! I'm just now catching up after the holiday week last week `=)`

Anyway, thanks for the background on `contact records`, hah. I had no idea it was so contentious. As you can tell, we didn't really put much thought into the `author` field other than, "This seems useful."

While we haven't discussed this `author` field, specifically, in every other issue we have been very careful not to try and create new standards where others exist (which is one of the reasons the spec references so many other standards). So, yes, if you could make a suggestion for how to specify that contact reference, that would be excellent!

**Comment by bhilburn** [comment]
@dharasty - Just a ping, here. I would really love to get your suggested changes for this merged ASAP! Is this something you're able to take on? =)

**Comment by bhilburn** [comment]
Now planning to use json-ld to properly cite authorship in v0.1.0

**Comment by bhilburn** [comment]
We need a short-term solution for v1.0.0 that's not json-ld, and also not something "new".

Proposal: we use a format that's shared with git and also commonly understood by other tools. Namely:

```txt
"Bruce Wayne <wayne@example.com>"
```

(a la `git commit --author="Bruce Wayne <wayne@example.com>"`)

**Comment by bhilburn** [comment]
Closed by #125
