### ISSUE TITLE
Extension Namespace: `antenna`

### ISSUE THREAD

**Issue by dharasty** [gnuradio/SigMF#81]
Is there prior art for a standard way to describe an "antenna pattern"?  By that I mean either a 2D or 3D representation of gain along the antenna's nominal "beam", AND the direction that the beam is "pointed".  (Note that this pattern may be parametric in frequency, as well.)

I'd like to propose that SigMF would be enhanced if it could capture this information in the metadata.

I can consider four subtending use cases:
1) Fixed position / fixed pointing.
    -- example: broadcast antenna.
2) Time-varying position / fixed pointing (or omni antenna).
    -- example: mobile telephony.
3) Fixed position / time-varying pointing.
    -- example: radar.
4) Time-varying position / time-varying pointing.
    -- example: certain exotic military applications.

Let's discuss the first item -- fixed position antenna / fixed pointing -- first.   (If we can't solve that -- or have no interest -- then then al the time-varying cases are moot...)

**Comment by bhilburn** [comment]
Hey @dharasty! No, we have not yet figured out how to describe antennas, yet, but it was identified as an important problem early on (back in #4).

Regarding time-varying stuff: we have decided on a way of handling this in #55 (it's just waiting on someone [*ahem* me *ahem*] to find the time to write it up). So, if we figure out a way to describe antennas, we should be able to just carry it over assuming we design it properly such that it's compatible with our plans in #55.

So, it seems to me that there are three separate items, here:

1. The antenna pattern
2. The antenna position
3. The antenna azimuth

For (2) and (3), we can follow our plan for describing fields that can be fixed or volatile, per #55. Describing (2) should just be the same geographic coordinates that we choose in #73 for the receiver geolocation. I'll leave those discussions to those issues to keep things focused.

So, that leaves two open questions, here, I think:

1. How do we describe antenna pattern?
2. How do we describe antenna azimuth?

Do you have any thoughts on these? Per usual, we don't want to create new standards where standards already exist, so the big question, is, what are good already existing standards for describing these?

**Comment by bhilburn** [comment]
Per my update to #4, this is all going into an extension namespace. I'll take a quick crack at it, but I'm not sure how patterns & azimuths should be described. Suggestions, anyone?

**Comment by djanderson** [comment]
We took a stab at an antenna object in a namespace extension here: https://github.com/NTIA/sigmf-ns-scos#antenna-object

Definitely interested in hearing other ideas as well.

**Comment by MichaelCotton** [comment]
sigmf-ns-scos Antenna object that @djanderson refers to above lists static antenna parameters. Also notice a start to dynamic parameters at https://github.com/NTIA/sigmf-ns-scos#dynamicantennasettings-object

**Comment by bhilburn** [comment]
Doug, Mike, these are great. I see a few things I think I would like to
tweak for merge, but you've largely addressed the problem.

Are you up for submitting them in a PR in an extension namespace? We can
iterate together to get it merged.

**Comment by bradeales** [comment]
PR #96 proposed.

**Comment by bhilburn** [comment]
Thanks so much to @bradeales, @MichaelCotton, and @djanderson! They have upstreamed the NTIA's `antenna` extension, which is now one of the canonical extensions in SigMF.

Great work, everyone!
