### ISSUE TITLE
Cite SigMF

### ISSUE THREAD

**Issue by dimitriblock** [gnuradio/SigMF#83]
Is there a proper way to cite SigMF in scientific publications?

**Comment by bhilburn** [comment]
Hey @dimitriblock! So sorry for the delayed response! Last week was a holiday week here in the US, and I'm just catching up on stuff.

Great question, and you are the first to ask it!

Here's my first pass at it:

`The Signal Metadata Format (SigMF), <version>, <date of commit used by reference>, <commit hash>, sigmf.org`

So, for example, if you were to reference the current spec, it would be:

```
The Signal Metadata Format (SigMF), v0.0.1, Oct 25 2017, d01f0c7, https://sigmf.org
```

Thoughts? Suggestions?

**Comment by dimitriblock** [comment]
@bhilburn thank you very much! This is fine for now

Maybe in future, SigMF should have a persistent identifier DOI for every release.

For example via Zenodo or Figshare

**Comment by bhilburn** [comment]
@dimitriblock - Ah, I'm not familiar with how those projects handle it. If you're up for it, it would be great to get a PR for doing it better!

**Comment by dimitriblock** [comment]
According to GitHub only the repo owner may create DOIs for each release https://guides.github.com/activities/citable-code

**Comment by bhilburn** [comment]
Added something to the spec as of b7afafe1b60. Will use that DOI process you linked, @dimitriblock, for the next release =)
