### ISSUE TITLE
'altitude' field, and being able to put coordinates in global

### ISSUE THREAD

**Issue by 777arc** [gnuradio/SigMF#84]
I reviewed the current version of SigMF to see if it would work for what I'm doing, and the only thing that would be nice to add is an optional altitude field after the latitude and longitude.  I mean it's optional so people without altitude can just leave it empty.

Another aspect that seems a little weird is that I can't just put the coordinates in global, which applies to the entire dataset.  For what I'm doing there's a set of coordinates that goes along with every file.  With the current SigMF I suppose I can just add an annotation to the first sample in each file, with a sample_count of either 1 or the number of samples in the dataset.  I guess that works, it just feels a little weird.  I think a lot of applications involve saving coordinates that don't change over a file and may never change =)

Also I think it was already mentioned but we need to decide on a standard coordinate system/units.  Doesn't matter, just needs to be standardized to save headache.

**Comment by bhilburn** [comment]
@777arc - Check out #73! We came up with the exact same suggestion :) Be sure to check out the discussion, there, and comment.

Now, the one thing that is still undecided is how, exactly, we describe geolocation. Ideally we identify a standard that includes not just lat/long but also altitude, somehow. I'm honestly not sure if that exists, though.

Do you have any knowledge of how to do this properly? Pinging @dharasty in case he has thoughts.

**Comment by 777arc** [comment]
I would say go with what KML uses, which is decimal degrees for lat/lon, and meters for altitude.  You also need an altitude-mode that chooses between:

1- distance from the surface of the Earth (relativeToGround)
2- distance above sea level (absolute)
3- distance from the bottom of major bodies of water (relativeToSeaFloor)

So four fields total

**Comment by bhilburn** [comment]
Will address in v0.0.2

**Comment by bhilburn** [comment]
@777arc  - any chance you can recommend another published standard / RFC / etc., to reference for this?

**Comment by jacobagilbert** [comment]
@bhilburn OGC KML (https://www.ogc.org/standards/kml/) is the name for what @777arc recommended and its pretty common and sane. I think this would be a good choice for the fix for this and #73 .
