### ISSUE TITLE
Extension: Transformed Data

### ISSUE THREAD

**Issue by mormj** [gnuradio/SigMF#88]
Hi,

I'm new to SigMF, but interested in using the format and tools to annotate both raw I/Q data and subsequent transforms on this data (STFT, Wavelet Decomposition, etc.).  The general idea was touched upon in #62 to store some other transformed representation of the data, such as PSD bins, but I feel this could be made very broad.  

A specific use case / example I can imagine is that some processing is done in the radio hardware, which might spit out averaged PSD bins over time instead of raw IQ.  It still would be useful to have a standardized method of annotating this, including the FFT window used, the averaging window, etc.  

Would these types of annotation fields be something that could live in a "Transforms" namespace, or is this altogether not a valid use case of SigMF?

Thanks,
Josh

**Comment by bhilburn** [comment]
Hey @mormj! Sorry for the delayed response, here.

You have a really great example use-case for where the discussion in #62 (@Teque5) would be useful. I actually hadn't thought about the fact that some radios don't even give you raw IQ.

I think the last question you asked, `is this altogether not a valid use case of SigMF?`, is the first thing we need to address. SigMF was originally designed to store recordings of digital samples, not transforms of digital data, so there are a lot of assumptions in the spec that might fundamentally break this.

For sure the only option would be to store the transforms in another file described by an extension namespace. It would kind of be replacing the using `.sigmf-data` file, though, which is fundamentally disallowed by the (current) spec describing extensions.

On one hand, I think it's pretty clear this is a large deviation from the design goal of SigMF. At the same time, though, if you were to try to design your own solution, it would probably end up looking a lot like SigMF, anyway.

I'm interested in hearing other opinions on this. We could allow it by expanding the scope of what extension namespaces are allowed to modify.

**Comment by mormj** [comment]
I'd be interested to hear other opinions as well, but I've found SigMF to to be a valuable format for storing and annotating transformed data (mainly STFT).  I'd propose an optional "transforms" namespace - the parameters to describe a frequency domain decomposition with averaging, like you would find on a spectrum analyzer, are limited and could be encapsulated in a namespace without ambiguity, and this could be expanded to any number of well defined transforms.

**Comment by bhilburn** [comment]
Okay, per my latest comment in #62, including transforms of the data will not be part of the `core` namespace. We need to decide, here, how we want to handle it.

We for sure don't want to try and describe what are `valid` ways to transform the data, so I think the real question, here, is should we provide a way to include arbitrary other files in a SigMF Archive, and if so, should we / how should we describe what that is?

Realistically, as the spec is currently written, applications could do whatever they want in folders not called out by the SigMF spec, including loading them up with spectrograms, for example. Is that enough?

My inclination is to roll with that as it keeps the spec simple, but it really doesn't solve the problem. Open to hearing thoughts / ideas of how to address this, though.

**Comment by bhilburn** [comment]
Going to close this one out, but I think we've hit on the agreed resolution for how to do this - it's an extension namespace. I think this could be written such that it is usable in both v0.1.0 and v0.0.2 - just a matter of someone that needs it putting it together, I think.

**Comment by cg-sat** [comment]
@mormj See https://github.com/sigmf/SigMF/issues/62#issuecomment-3023109917 for our solution on storing spectrogram data in SigMF format. That should also work for STFFT data.
