### ISSUE TITLE
use 'utf-8' instead of 'ascii'

### ISSUE THREAD

**Issue by jdemel** [gnuradio/SigMF#9]
In 'sigmf-spec.md':

> string: A string of ASCII characters, as defined by the JSON standard.

should be changed to

> string: A string of UTF-8 characters, as defined by the JSON standard.

I'm not familiar with JSON, but from looking at the provided links, it seems like ECMA-404 refers to strings as UTF8 characters. 

> A string is a sequence of zero or more Unicode characters, wrapped in double quotes, using backslash escapes. A character is represented as a single character string. A string is very much like a C or Java string.

Also, UTF8 is probably required as soon as non-english users get involved.

**Comment by kpreid** [comment]
More correctly, specifying which encoding to use should be said about _the entire JSON document,_ not individual string values occurring in it. (And then, yes, it should be UTF-8.)

**Comment by bhilburn** [comment]
Please review #11 - thanks!
