### ISSUE TITLE
Ordering of annotation segments with the same sample_start?

### ISSUE THREAD

**Issue by pwicks86** [gnuradio/SigMF#90]
If a SigMF recording has two annotation segments with the same `sample_start` value but different `sample_count` values, should there be a defined ordering between them?

**Comment by bhilburn** [comment]
Great question! And you're right, the spec is totally ambiguous about how to handle this.

I can't think of a reason why an ordering would matter, so I'm partial to not specifying a hard rule, here, so as not to add complexity to reader applications. Can you think of any reason why it should matter, @pwicks86?

**Comment by pwicks86** [comment]
I can't think of any specific reason it should matter, just something I came across while implementing the spec.

**Comment by bhilburn** [comment]
Added a note clarifying that there is no defined ordering and pushed to master!
