### ISSUE TITLE
Is the first capture segment required to have a core:sample_start of 0?

### ISSUE THREAD

**Issue by pwicks86** [gnuradio/SigMF#93]
In a SigMF recording, is it allowable to have the first capture segment in the segments array have a `core:sample_start` with a value greater than 0? As an example, if you had a file where the first `N` samples were known to be bad due to a device warmup or something like that, then the first capture segment would have a `core:sample_start` of `N+1`.

If it is allowed to have a `core:sample_start` greater than 0, then what is the responsibility of a conforming reader application when handling the recording? Should it ignore all data in the data file before the first capture segment?

**Comment by pwicks86** [comment]
> It's been a couple of months since you posted this - do you still agree with the above?

Pretty much yeah. The one wrinkle is that using the `core:sample_start` field this way only works if you know that the number of bytes you want to skip at the beginning of the file is a multiple of the sample size. So if you had a sample size of 8 and you knew that the first 100 bytes of a data file were bad for some reason, then you'd have to round up and lose a bit of valid data. I don't know if that's worth adding a separate field to handle that case though.

**Comment by bhilburn** [comment]
Fair point if there is an arbitrary number of bytes at the head of the file, but I think the safest option is probably just to require boundaries based on sample size. Let's close this one out, for now, and we can circle back around if this turns out to be a problematic decision.
